### ISSUE TITLE
Debian package waiting for review

### ISSUE THREAD

**Issue by markusgattol** [zealdocs/zeal-packaging#3]
jfyi: there's a Debian package on the NEW queue https://ftp-master.debian.org/new/zeal_20141123-1.html

Sitting there, waiting for review for 8 months though...

**Comment by trollixx** [comment]
See https://tracker.debian.org/pkg/zeal. As of today the latest version of Zeal has been added to Debian unstable. I guess this issue can be considered resolved.

**Comment by trollixx** [comment]
Oh, I just realised that the email about this was from you :)

**Comment by sammy44nts** [comment]
ChangZhuo Chen (陳昌倬) <czchen@gmail.com> is the maintainer for the debian package and made it to reach the testing repository. [Debian Quality Assurance](https://qa.debian.org/developer.php?login=czchen%40gmail.com)
I think this package will never find its way to the stable repository while the "unreproducible build" issue is not solved. ([How to solve this issue](https://reproducible.debian.net/rb-pkg/testing/amd64/zeal.html))

Am I wrong ?

**Comment by trollixx** [comment]
I am not sure, but you might be right. @czchen are reproducible builds required for Debian?

**Comment by czchen** [comment]
@trollixx Currently reproducible builds is not required for stable.

The current unreproducible build is caused by `__DATE__` and `__TIME__` macros. I can patch it in Debian to see if it is reproducible or not. However, currently Debian is in GCC5 transition now, so I won't do it until the transition is over.

**Comment by sammy44nts** [comment]
@czchen I do not find libqt5sql5-sqlite in /debian/control Build-Depends. I think issue #4 will apply if this package was not already install on the user debian OS.

**Comment by czchen** [comment]
@sammy44nts Thank for the report. Could you help to send a bug report to Debian via reportbug?

**Comment by sammy44nts** [comment]
Done, sorry for the delay.

**Comment by czchen** [comment]
@sammy44nts These issues are fixed in Debian (https://tracker.debian.org/pkg/zeal), thanks for the bug reports.

As for "unreproducible build", my plan is waiting for SOURCE_DATE_EPOCH patch in GCC. After the patch is in GCC, we will have a reproducible build. See https://wiki.debian.org/ReproducibleBuilds/TimestampsFromCPPMacros for more information.
