### ISSUE TITLE
Slackbuild for Slackware available

### ISSUE THREAD

**Issue by richarson** [zealdocs/zeal-packaging#5]
Hello, I made a Slackbuild for Slackware 14.1, can be found at:

http://slackbuilds.org/repository/14.1/development/zeal/?search=zeal

I'm not sure this is the right channel for this, but I wanted to let you know and ask if it's possible to mention it in the donwload page.

Thanks in advance :)

**Comment by trollixx** [comment]
Hi, thanks! The right repository would be [zealdocs.github.io](zealdocs/zealdocs.github.io), but it's not a problem, I have just added the link.

There's an issue with the version string in 0.1.1. You should to set `ZEAL_VERSION` to `0.1.1` prior to calling `qmake`, otherwise it would use `0.0.0` version and notify about available update. Hopefully I'll release 0.1.2 this weekend as well, which fixes this problem among many others.

**Comment by richarson** [comment]
Great, thank you!

I'll add ZEAL_VERSION to the slackbuild and see if I can resubmit it, otherwise I'll just wait for 0.1.2 and kill two birds with one stone :)
